version: '3'
services:
  ruby:
    container_name: nkr_ruby
    build:
      context: ./rails
      dockerfile: docker/ruby/Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    tty: true
    stdin_open: true
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nkr_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
  kong:
    build:
      context: .
      dockerfile: docker/kong/Dockerfile
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-postgres
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_LISTEN_SSL: "0.0.0.0:8444"
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    volumes:
      - ./docker/kong:/opt/scripts
    command: ["sh", "/opt/scripts/wait-for-postgres.sh", "kong-postgres", "5432", "kong", "--", "kong", "start", "--vv"]
    depends_on:
      - kong-postgres
  kong-postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - 15432:5432
    volumes:
      - kong-postgres-volume:/var/lib/postgresql/data
  kong-dashboard:
    image: pgbi/kong-dashboard:v3.5.0
    ports:
      - 8080:8080
    command: ["start", "--kong-url", "http://kong:8001"]
    depends_on:
      - kong
  nuxt:
    build:
      context: .
      dockerfile: docker/yarn/Dockerfile
    environment:
      HOST: "0.0.0.0"
    ports:
      - 3030:3000
    command: ["run", "dev"]
    volumes:
      - ./nuxt:/app
      - node-modules-volume:/app/node_modules
  yarn:
    build:
      context: .
      dockerfile: docker/yarn/Dockerfile
    volumes:
      - ./nuxt:/app
      - node-modules-volume:/app/node_modules
  vue:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile
    volumes:
      - ./nuxt:/app
      - node-modules-volume:/app/node_modules

volumes:
  bundle-volume:
  db-volume:
  node-modules-volume:
  kong-postgres-volume:
